/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testJsonReader() throws FileNotFoundException {
        BufferedReader reader = new BufferedReader(new FileReader("src/recentquotes.json"));
        assertNotNull(String.valueOf(reader), "testJsonReader should return: "
                );
    }

    @Test
    void testConstructorQuote() {
        Quote quote= new Quote(null, "Doaa", "i like nthn", "i hate everythin");
        assertEquals(null, quote.getTags());
        assertEquals("Doaa", quote.getAuthor());
        assertEquals("i like nthn", quote.getLIKES());
        assertEquals("i hate everythin", quote.getText());
    }

    @RepeatedTest(50)
    @Test
    public void testRandomQuote() throws FileNotFoundException{
        Gson gson = new Gson();
        int idx =0;
        BufferedReader reader = new BufferedReader(new FileReader("src/recentquotes.json"));
        List<Quote> quote = gson.fromJson(reader, new TypeToken<List<Quote>>() {}.getType());
        int min = 0;
        int max = quote.size()-1 ;
        Quote quote1 = quote.get((int) (Math.random()*(max- min+1)+ min));
        for(int i = 0; i < quote.size(); i++) {
            if(quote.get(i).getText().equals(quote1.getText())){
                idx = i;
            }
        }
        assertNotEquals(idx >= 0 && idx < quote.size()-1 , "return true if successfully got a random quote from the json file ");
    }

    @Test
    public void testAPI() throws IOException {
        URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        assertEquals(200, connection.getResponseCode(), String.valueOf(true));
    }

}


