///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//
///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package quotes;
//
//import com.google.gson.Gson;
//import com.google.gson.reflect.TypeToken;
//
//import java.io.BufferedReader;
//import java.io.FileReader;
//import java.io.IOException;
//
//import java.util.List;
//
//public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }
//
//    public static void main(String[] args) throws IOException {
//        System.out.println(new App().getGreeting());
//
//
//        Gson gson = new Gson();
//
//        BufferedReader reader = new BufferedReader(new FileReader("app/src/recentquotes.json"));
//        List<Quote> quote = gson.fromJson(reader, new TypeToken<List<Quote>>() {}.getType());
//        int min = 0;
//        int max = quote.size()-1 ;
//        System.out.println(quote.get((int) (Math.random()*(max- min+1)+ min)).toString());
//    }
//}

package quotes;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        System.out.println(new App().getGreeting());


        Gson gson = new Gson();

        BufferedReader reader = new BufferedReader(new FileReader("app/src/recentquotes.json"));
        List<Quote> quote = gson.fromJson(reader, new TypeToken<List<Quote>>() {}.getType());
        int min = 0;
        int max = quote.size()-1 ;
        System.out.println(quote.get((int) (Math.random()*(max- min+1)+ min)).toString());

//        BufferedReader in = new BufferedReader(new FileReader("app/src/recentquotes.json"));
//        System.out.println(in.readLine());
//
//        System.out.println("++++++++++++++++++++++++++++ GSON CONVERSION TO JSON ++++++++++++++++++++++++++++");



    }
//    private static <Gson> String convertToJson(Quote quote) {
//
//        GsonBuilder builder = new GsonBuilder();
//        Gson gson = builder.create();
//
//        System.out.println(gson.toJson(quote));
//        return gson.toJson(quote);
//    }
}
